### ISSUE TITLE
Project cannot run

### ISSUE THREAD

**Issue by jiaoxinwei** [Eskils/DitheringEngine#1]
Project cannot run
We can give you an OC version
Or I can give you a contact information, I would like to learn from you privately

**Comment by Eskils** [comment]
Thank you for making me aware that the demo application was not compiling. This has been fixed, and the documentation has been updated to reflect changes since the previous release.

There are many great resources online to learn about dithering algorithms. If you are interested, I would advise you to read Wikipedia pages covering the algorithms. The pages are relatively concise and have good coverage on implementation details.

Cheers!
